#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : snitun
Version  : 0.20
Release  : 7
URL      : https://github.com/NabuCasa/snitun/archive/0.20/snitun-0.20.tar.gz
Source0  : https://github.com/NabuCasa/snitun/archive/0.20/snitun-0.20.tar.gz
Summary  : SNI proxy with TCP multiplexer
Group    : Development/Tools
License  : GPL-3.0
Requires: snitun-license = %{version}-%{release}
Requires: snitun-python = %{version}-%{release}
Requires: snitun-python3 = %{version}-%{release}
Requires: async-timeout
Requires: attrs
Requires: cryptography
BuildRequires : async-timeout
BuildRequires : attrs
BuildRequires : buildreq-distutils3
BuildRequires : cryptography
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
# SniTun
End-to-End encryption with SNI proxy on top of a TCP multiplexer
## Connection flow

%package license
Summary: license components for the snitun package.
Group: Default

%description license
license components for the snitun package.


%package python
Summary: python components for the snitun package.
Group: Default
Requires: snitun-python3 = %{version}-%{release}

%description python
python components for the snitun package.


%package python3
Summary: python3 components for the snitun package.
Group: Default
Requires: python3-core
Provides: pypi(snitun)

%description python3
python3 components for the snitun package.


%prep
%setup -q -n snitun-0.20
cd %{_builddir}/snitun-0.20

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582921292
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/snitun
cp %{_builddir}/snitun-0.20/LICENSE %{buildroot}/usr/share/package-licenses/snitun/31a3d460bb3c7d98845187c716a30db81c44b615
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/snitun/31a3d460bb3c7d98845187c716a30db81c44b615

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
