#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : snitun
Version  : 0.19
Release  : 4
URL      : https://github.com/NabuCasa/snitun/archive/0.19.tar.gz
Source0  : https://github.com/NabuCasa/snitun/archive/0.19.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: snitun-license = %{version}-%{release}
Requires: snitun-python = %{version}-%{release}
Requires: snitun-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
# SniTun
End-to-End encryption with SNI proxy on top of a TCP multiplexer
## Connection flow

%package license
Summary: license components for the snitun package.
Group: Default

%description license
license components for the snitun package.


%package python
Summary: python components for the snitun package.
Group: Default
Requires: snitun-python3 = %{version}-%{release}

%description python
python components for the snitun package.


%package python3
Summary: python3 components for the snitun package.
Group: Default
Requires: python3-core

%description python3
python3 components for the snitun package.


%prep
%setup -q -n snitun-0.19

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1555692500
export LDFLAGS="${LDFLAGS} -fno-lto"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/snitun
cp LICENSE %{buildroot}/usr/share/package-licenses/snitun/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/snitun/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
